---
# vars file for add_pve_group
# inputs
# userid needs to be configured as follows: username@pam
add_pve_group_name:
add_pve_group_comment:
add_pve_group_email:
add_pve_group_firstname:
add_pve_group_lastname:
add_pve_group_password:

# internals
add_pve_group_domain_name: https://192.168.0.2:8006
