---
- name: Swap proxmox from wireless to wired
  hosts: all
  gather_facts: true
  vars_files:
    - vars/secrets.yml
  vars:
    hostname: "{{ ansible_facts['hostname'] }}"
    line_indent: "      "
  tasks:
    - name: Add required packages
      ansible.builtin.package:
        name: network-manager
        state: present
    - name: Enable interface management for Network Manager
      ansible.builtin.lineinfile:
        path: /etc/NetworkManager/NetworkManager.conf
        regexp: "^managed="
        line: "managed=true"
      become: true
      notify:
        - Restart Network Manager service
    - name: Add an Ethernet connection with static IP configuration
      community.general.nmcli:
        conn_name: conn_eth
        ifname: eth0
        type: ethernet
        ip4: "192.168.0.12/24"
        gw4: "192.168.0.1"
        state: present
        conn_reload: true
      become: true
      notify:
        - Disable wireless
    - name: Enable conn_eth
      community.general.nmcli:
        conn_name: conn_eth
        state: up
      become: true
      notify:
        - Disable wireless
    - name: Update /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "{{ hostname }}"
        line: "192.168.0.12{{ line_indent }}{{ hostname }}"
      become: true
  handlers:
    - name: Restart Network Manager service
      ansible.builtin.service:
        name: NetworkManager
        state: restarted
    - name: Disable wireless
      block:
        - name: Set connection to down
          community.general.nmcli:
            conn_name: preconfigured
            state: down
          become: true
          async: 45
          poll: 5

        - name: Update wireless connection autoconnect
          community.general.nmcli:
            conn_name: preconfigured
            ifname: wlan0
            # type: wifi
            autoconnect: false
            state: present
          become: true
