---
# vars file for add_pve_user
# inputs
# userid needs to be configured as follows: username@pam
add_pve_user_userid:
add_pve_user_email:
add_pve_user_firstname:
add_pve_user_lastname:
add_pve_user_password:

# internals
add_pve_user_domain_name: https://192.168.0.2:8006
