---
- name: Configure fileserver vm
  hosts: fileserver
  gather_facts: true
  vars_files:
    - ../vars/secrets.yml
  vars:
    packages:
      - vim
      - wget
      - htop
      - samba
    repositories:
      - url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        disable_gpg_check: true
      # The free repo MUST be enabled before the nonfree
      - url: https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-9.noarch.rpm
        disable_gpg_check: true
      - url: https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-9.noarch.rpm
        disable_gpg_check: true
  tasks:
    - name: Update subscription-manager
      ansible.builtin.command:
        cmd: "subscription-manager repos --enable codeready-builder-for-rhel-9-{{ ansible_architecture }}-rpms"
      become: true

    - name: Add repository
      ansible.builtin.dnf:
        name: "{{ item.url }}"
        state: present
        disable_gpg_check: "{{ item.disable_gpg_check }}"
      loop: "{{ repositories }}"
      become: true

    - name: update dnf cache
      ansible.builtin.dnf:
        update_cache: yes

    - name: Install additional packages
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
      become: true

    - name: Configure samba
      ansible.builtin.template:
        src: ../../templates/smb.conf.j2
        dest: /etc/samba/smb.conf
        mode: "0644"
      become: true

    - name: Add smbgroup
      ansible.builtin.group:
        name: smbgroup
        state: present
        system: true
      become: true

    - name: Add smbuser
      ansible.builtin.user:
        name: smbuser
        comment: Samba user
        group: smbgroup
        create_home: false
        system: true
        shell: /bin/false
      become: true

    - name: Create a new ext4 primary partition
      community.general.parted:
        device: /dev/vdb
        number: 1
        state: present
        fs_type: ext4
        label: gpt
      become: true
      tags:
        - mount

    - name: Create filesystem on new partition
      community.general.filesystem:
        fstype: ext4
        dev: /dev/vdb1
      become: true

    - name: Mount partition
      ansible.posix.mount:
        path: /srv
        src: /dev/vdb1
        state: mounted
        fstype: ext4
      become: true
      tags:
        - mount

    - name: Make share directories
      ansible.builtin.file:
        path: "{{ item }}"
        owner: smbuser
        group: smbgroup
        mode: "0775"
        state: directory
      become: true
      loop:
        - /srv/samba/public
        - /srv/samba/protected

    # Needs firewalld, and python-firewall
    - name: Configure firewall
      ansible.posix.firewalld:
        service: samba
        state: enabled
        permanent: true
        immediate: true
      become: true

    - name: Start and enable daemon
      ansible.builtin.service:
        name: smb
        state: restarted
        enabled: true
      become: true
      
    - name: Set samba account
      ansible.builtin.shell:
        cmd: "(echo '{{ smb_password }}'; echo '{{ smb_password }}') | sudo smbpasswd -a {{ smb_username }} -s"
      become: true
      no_log: true