---
- name: Get user id
  ansible.builtin.uri:
    url: "{{ domain_name }}/api2/json/access/users"
    method: GET
    headers:
      Cookie: "PVEAuthCookie={{ ticket }}"
    validate_certs: false
    status_code: 200
  register: users_response
- name: Print
  ansible.builtin.debug:
    var: users_response
    verbosity: 1