---
- name: Create proxmox users
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/secrets.yml
  roles:
    - role: add_pve_user
      vars:
        add_pve_user_userid: gelzibar@pam
        add_pve_user_email: anjo.hill@gmail.com
        add_pve_user_firstname: Andrew
        add_pve_user_lastname: Hill
        add_pve_user_password: "{{ hillhouse_user_password }}"

    - role: add_pve_user
      vars:
        add_pve_user_userid: packer@pve
        add_pve_user_email: anjo.hill@gmail.com
        add_pve_user_firstname: Packer Service Account
        add_pve_user_password: "{{ packer_password }}"
