---
- name: Create proxmox users
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/secrets.yml
    - vars/test_users.yml
  tasks:
    - name: Create cookie ticket
      ansible.builtin.include_role:
        name: shellbender.pve.create_ticket
      vars:
        create_ticket_username: root@pam
        create_ticket_password: "{{ hillhouse_root_password }}"
    - name: Create core set of users
      ansible.builtin.include_role:
        name: shellbender.pve.create_user
      vars:
        create_user_details: "{{ test_user }}"
