---
- name: Add ssh config
  ansible.builtin.blockinfile:
    path: ~/.ssh/config
    create: true
    mode: "0644"
    append_newline: true
    prepend_newline: true
    block: |
      Host {{ register_ssh_nickname }}
          HostName {{ register_ssh_hostname }}
          User {{ register_ssh_user }}
          IdentityFile ~/.ssh/id_ed25519
- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ register_ssh_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  delegate_to: "{{ register_ssh_hostname }}"
