---
- name: Configure proxmox node
  hosts: all
  gather_facts: false
  tasks:
    - name: Copy .bashrc profile
      ansible.builtin.copy:
        dest: /root
        src: /home/andrew/.bashrc
        mode: "0644"
      become: true
    - name: Install essential packages
      ansible.builtin.package:
        name: lshw
        state: present
      become: true
